project:
  type: website
  output-dir: docs/en  

website:
  site-url: "https://raymz1990.github.io"
  google-analytics: "G-NYKKWQWQLX"
  title: "Raymundo Eduardo Pilz"
  favicon: "static/favicon.svg"
  page-navigation: true
  search: false
  open-graph: 
    site-name: raymundo's website
    description: "Raymundo Pilz's website about work, graphics and statistics"
    image: "static/img/avatar.svg"
  navbar:
    pinned: true
    logo: "static/logo.svg"
    title: false
    background: primary
    left:
      - href: content/experience/index.en.qmd  
        text: Experience 
      - href: content/education/index.en.qmd   
        text: Education 
      - href: content/project/index.en.qmd     
        text: Projects
    right:
      - href: index.qmd
        text: "{{< iconify emojione flag-for-brazil >}}"
      - href: en/index.qmd
        text: "{{< iconify emojione flag-for-spain >}}"
  
  page-footer:
    left: |
      <b> © 2024 Raymundo Eduardo Pilz</b> | powered by [Quarto](https://quarto.org)
    right: 
      - href: https://github.com/raymz1990
        text: "{{< iconify fa6-brands github >}}"
        target: _blank
        rel: me
      - href: https://www.linkedin.com/in/raymundopilz/
        text: "{{< iconify entypo-social linkedin-with-circle >}}"
        target: _blank
        rel: me

  back-to-top-navigation: false

format:
  html:
    theme: 
      light: [flatly, assets/theme/theme-light.scss]
      dark: [flatly, assets/theme/theme-dark.scss]
    css: 
      - assets/css/styles.css
      - assets/css/academicons.css
    code-copy: true
    code-overflow: wrap
    toc: true
    highlight-style: zenburn
    code-fold: true
    code-link: true
    link-external-icon: false
    link-external-newwindow: true

execute: 
  freeze: auto
