project:
  type: website
  output-dir: docs
  
website:
  site-url: "https://raymz1990.github.io"
  #repo-url: "https://raymz1990.github.io"
  google-analytics: "G-NYKKWQWQLX"
  title: "Raymundo Eduardo Pilz"
  favicon: "static/favicon.svg"
  search: false
  open-graph: 
    site-name: raymundo's website
    description: "Raymundo Pilz's website about work, graphics and statistics"
    image: "static/img/avatar.svg"
  navbar:
    pinned: true
    logo: "static/logo.svg"
    title: false
    background: primary
    left:
      - href: content/experience/index.qmd
        text: Experience 
      - href: content/education/index.qmd
        text: Education 
      - href: content/project/index.qmd
        text: Projects
    right:
      - href: https://github.com/raymz1990
        text: "[{{< fa brands github >}}]{class='quarto-navbar-tools-item'}"
        target: _blank
<<<<<<< HEAD
      - href: https://www.linkedin.com/in/raymundopilz/
=======
      - href: https://linkedin.com/raymundopilz
>>>>>>> 5bea3f2c02210c6f7705bd10938698d294cbc195
        text: "{{< iconify entypo-social linkedin-with-circle >}}"
        target: _blank
      - href: en/index.qmd
        text: "{{< iconify emojione flag-for-united-states >}}"
<<<<<<< HEAD
    tools:
=======
        target: _blank
>>>>>>> 5bea3f2c02210c6f7705bd10938698d294cbc195
  page-footer:
    center: |
      <b>© 2024 Raymundo Eduardo Pilz</b>  <br>
      powered by [quarto](https://quarto.org)
  back-to-top-navigation: false

format:
  html:
    theme: 
      light: [flatly, assets/theme/theme-light.scss]
      dark: [flatly, assets/theme/theme-dark.scss]
    css: 
      - assets/css/styles.css
      - assets/css/academicons.css
    code-copy: true
    code-overflow: wrap
    toc: true
    highlight-style: zenburn

execute: 
  freeze: auto