project:
  type: website
  output-dir: docs
  
website:
  site-url: "https://raymz1990.github.io"
  google-analytics: "G-NYKKWQWQLX"
  title: "Raymundo Eduardo Pilz"
  favicon: "static/favicon.svg"
  search: false
  open-graph: 
    site-name: raymundo's website
    description: "Raymundo Pilz's website about work, graphics and statistics"
    image: "static/img/avatar.svg"
  navbar:
    pinned: true
    logo: "static/logo.svg"
    title: false
    background: primary
    left:
      - href: content/experience/index.qmd
        text: Experience 
      - href: content/education/index.qmd
        text: Education 
      - href: content/project/index.qmd
        text: Projects
    right:
      - text: "{{< iconify fa6-brands github >}}"
        href: https://github.com/raymz1990
      - text: "{{< iconify entypo-social linkedin-with-circle >}}"
        href: https://linkedin.com/raymundopilz
      - text: "{{< iconify emojione flag-for-united-states >}}"
        href: en/index.qmd
  page-footer:
    center: |
      <b>© 2024 Raymundo Eduardo Pilz</b>  <br>
      powered by [quarto](https://quarto.org)

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: 
      - styles.css
      - academicons.css
    toc: true
    highlight-style: zenburn
execute: 
  freeze: auto