project:
  type: website
  output-dir: docs
  
website:
  site-url: "https://raymz1990.github.io"
  #repo-url: "https://raymz1990.github.io"
  google-analytics: "G-NYKKWQWQLX"
  title: "Raymundo Eduardo Pilz"
  favicon: "static/favicon.svg"
  search: false
  open-graph: 
    site-name: raymundo's website
    description: "Raymundo Pilz's website about work, graphics and statistics"
    image: "static/img/avatar.svg"
  navbar:
    pinned: true
    logo: "static/logo.svg"
    title: false
    background: primary
    left:
      - href: content/experience/index.qmd
        text: Experience 
      - href: content/education/index.qmd
        text: Education 
      - href: content/project/index.qmd
        text: Projects
    right:
      - href: https://github.com/raymz1990
        text: "[{{< fa brands github >}}]{class='quarto-navbar-tools-item'}"
        target: _blank
      - href: https://www.linkedin.com/in/raymundopilz/
        text: "{{< iconify entypo-social linkedin-with-circle >}}"
        target: _blank
      - href: en/index.qmd
        text: "{{< iconify emojione flag-for-united-states >}}"
  page-footer:
    center: |
      <b>© 2024 Raymundo Eduardo Pilz</b>  <br>
      powered by [quarto](https://quarto.org)
  back-to-top-navigation: false

format:
  html:
    theme: 
      light: [flatly, assets/theme/theme-light.scss]
      dark: [flatly, assets/theme/theme-dark.scss]
    css: 
      - assets/css/styles.css
      - assets/css/academicons.css
    code-copy: true
    code-overflow: wrap
    toc: true
    highlight-style: zenburn
    code-fold: true
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    grid:
      body-width: 1100px
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 1.5rem

execute: 
  freeze: auto