project:
  type: website
  resources: 
    - "*.mp4"

website: 
  site-url: "https://raymz1990.github.io"
  #repo-url: "https://raymz1990.github.io"
  google-analytics: "G-NYKKWQWQLX"
  title: "Raymundo Eduardo Pilz"
  favicon: "static/favicon.svg"
  search: false  

  open-graph: 
    site-name: Raymundo's website
    description: "Raymundo Pilz's website about work, graphics and statistics"
    locale: pt-BR

  page-footer:
    left: |
      <b>© 2024 Raymundo Eduardo Pilz</b> | 
      powered by [quarto](https://quarto.org)
    right: 
      - href: https://github.com/raymz1990
        text: "{{< iconify fa6-brands github >}}"
        target: _blank
        rel: me
      - href: https://www.linkedin.com/in/raymundopilz/
        text: "{{< iconify entypo-social linkedin-with-circle >}}"
        target: _blank
        rel: me

  back-to-top-navigation: false

profile:
  default: english
  group: [english, portuguese]
  
