---
pagetitle: "Experience"
page-layout: custom
toc: false
css: [css/index.css]
include-after-body:
  text: |
    <script src='/assets/js/styles.js'></script>
    <script src='/assets/js/non-posts.js'></script>
---

:::: light-mode

::::{.columns}
::: {.light-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.light-header}
GS RISK
:::
:::
:::
::::

:::: {.columns}
::: {.light-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [GS Risk](https://www.linkedin.com/company/gsrisk/?originalSubdomain=br)

Accounting Analyst <br>
**Nov 2022 – present** ● Curitiba, Paraná - Brazil 

* Economic and financial diagnosis and identification of weighting factors, from the perspective of credit risk;
* Calculation, analysis, and monitoring of Operational, Profitability, Liquidity, Debt and Equity Structure indicators, with graphs and reports developed in Power BI;
* Analysis and suggestion of improvements regarding the structure of financial statements in accordance with accounting legislation for the company's operating segment;
* Monitoring the performance and evolution of production financing contracts and compliance with contractual assumptions and limits, with graphs and reports developed in Power BI.

:::
:::
::::

::::{.columns}
::: {.light-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.light-header}
PRIDE
:::
:::
:::
::::

:::: {.columns}
::: {.light-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [Construtora e Incorporadora Pride S/A](https://www.construtorapride.com.br/)

Controller Analyst <br>
**Feb 2022 - Jul 2022** ● Curitiba, Paraná - Brazil 

* Economic and manageable data survey for calculation and presentation of results; 
* Development of operational and financial indicators;
* Supervision of sale variations regarding the planned and the fulfilled budgets;
* Support for the financial area with clearings and defauts evaluation in the regard of the company’s ledger, with detailed Power BI reports;
* Support for the accounting area on balance reports;
* Visualization and identification of management opportunities and improvements. 

:::
:::
::::

::::{.columns}
::: {.light-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.light-header}
LUDOVICO TOZZO
:::
:::
:::
::::

:::: {.columns}
::: {.light-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [Ludovico J Tozzo LTDA](https://ludovico-tozzo.com.br/)

Accounting Analist <br>
**Apr 2019 - Dec 2021** ● Chapecó, Santa Catarina - Brazil 

* Accounting entries | Accounting closing | Auditing;
* Incoming and outgoing tax books | Taxes retention | Tax calculation;
* Expense management | Expenses report | Cost control;
* Routines of payable financial accounts | File management | Contract reviews;
* Balance sheets | Management of tax documents.

:::
:::
::::

::::{.columns}
::: {.light-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.light-header}
LAC LELO
:::
:::
:::
::::

:::: {.columns}
::: {.light-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [Laticínios São João S/A](http://www.laclelo.com.br/)

Administrative Assistant <br>
**Dec 2012 – Apr 2019** ● São João do Oeste, Santa Catarina - Brazil 

* Billing | Incoming and outgoing invoices | Expense entry;
* Management reports | Performance and operational indicators; 
* Income statement | Products’ cost generation | Control of transport expenses;
* Data verification | Process mapping;
* Planning | Inventory control | Product management;
* Supplier and customer services | Sales

:::
:::
::::

::::

:::: dark-mode

::::{.columns}
::: {.dark-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.dark-header}
GS RISK
:::
:::
:::
::::

:::: {.columns}
::: {.dark-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [GS Risk](https://www.linkedin.com/company/gsrisk/?originalSubdomain=br)

Accounting Analyst <br>
**Nov 2022 – present** ● Curitiba, Paraná - Brazil 

* Economic and financial diagnosis and identification of weighting factors, from the perspective of credit risk;
* Calculation, analysis, and monitoring of Operational, Profitability, Liquidity, Debt and Equity Structure indicators, with graphs and reports developed in Power BI;
* Analysis and suggestion of improvements regarding the structure of financial statements in accordance with accounting legislation for the company's operating segment;
* Monitoring the performance and evolution of production financing contracts and compliance with contractual assumptions and limits, with graphs and reports developed in Power BI.

:::
:::
::::

::::{.columns}
::: {.dark-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.dark-header}
PRIDE
:::
:::
:::
::::

:::: {.columns}
::: {.dark-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [Construtora e Incorporadora Pride S/A](https://www.construtorapride.com.br/)

Controller Analyst <br>
**Feb 2022 - Jul 2022** ● Curitiba, Paraná - Brazil 

* Economic and manageable data survey for calculation and presentation of results; 
* Development of operational and financial indicators;
* Supervision of sale variations regarding the planned and the fulfilled budgets;
* Support for the financial area with clearings and defauts evaluation in the regard of the company’s ledger, with detailed Power BI reports;
* Support for the accounting area on balance reports;
* Visualization and identification of management opportunities and improvements. 

:::
:::
::::

::::{.columns}
::: {.dark-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.dark-header}
LUDOVICO TOZZO
:::
:::
:::
::::

:::: {.columns}
::: {.dark-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [Ludovico J Tozzo LTDA](https://ludovico-tozzo.com.br/)

Accounting Analist <br>
**Apr 2019 - Dec 2021** ● Chapecó, Santa Catarina - Brazil 

* Accounting entries | Accounting closing | Auditing;
* Incoming and outgoing tax books | Taxes retention | Tax calculation;
* Expense management | Expenses report | Cost control;
* Routines of payable financial accounts | File management | Contract reviews;
* Balance sheets | Management of tax documents.

:::
:::
::::

::::{.columns}
::: {.dark-section}
::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

::: {.dark-header}
LAC LELO
:::
:::
:::
::::

:::: {.columns}
::: {.dark-bg}

::: {.column .col-v-center width="15%"}
:::

::: {.column .col-v-center width="70%"}

## [Laticínios São João S/A](http://www.laclelo.com.br/)

Administrative Assistant <br>
**Dec 2012 – Apr 2019** ● São João do Oeste, Santa Catarina - Brazil 

* Billing | Incoming and outgoing invoices | Expense entry;
* Management reports | Performance and operational indicators; 
* Income statement | Products’ cost generation | Control of transport expenses;
* Data verification | Process mapping;
* Planning | Inventory control | Product management;
* Supplier and customer services | Sales

:::
:::
::::

::::